include:
  - project: devops/ci-template
    ref: v1.4.3
    file: GitlabFlow/Deploy-custom.yml

variables:
  HELM_RELEASE_PREFIX: bios-multilevel

build-bios-multilevel:
  extends: .build
  rules:
    - !reference [.build, rules]
    - when: on_success

production-bios-multilevel:
  extends: .production
  stage: deploy
  environment:
    url: https://bios.barrage.net
  needs:
    - job: build-bios-multilevel
      optional: true
  rules:
    - !reference [.production, rules]
    - when: on_success
